# appspec.yml
version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: root
  
  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/verify_container.sh
      timeout: 60
      runas: root

  ValidateService:
    - location: scripts/health_check.sh
      timeout: 60
      runas: root